# Generated by Django 5.2.3 on 2025-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vote_signature"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vote",
            name="public_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="receipt",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
    ]
